name: .NET Build

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 * * * *' # Ejecuta cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Altere para la versión necesaria

      # - name: Restore dependencies
      #   run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Simple script
        run: echo "Este es un script simple ejecutado cada hora"