name: .NET Build

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 * * * *' # Ejecuta cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Actualizado para usar .NET 8.0

      - name: Run a pre-existing GitHub Action
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/github4women.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build project
        run: dotnet build github4women/github4women.csproj --no-restore --configuration Release

      - name: Simple script
        run: echo "Este es un script simple ejecutado cada hora"